### To generate the output file to partially incorporate in the README.md,
### Execute this command in the Terraform module's code folder:
# terraform-docs -c ../tfdocs-config.yml .

formatter: "markdown table" # this is required

content: |-
  ## Main.tf file content

  Please replace the modules source and version with your relevant information

  ```hcl
  {{ include "main.tf" }}
  ```
  {{ .Modules }}
  {{ .Requirements }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}

output:
  file: ./README.md
  mode: inject
  template: |-
      <!-- BEGIN_AUTOMATED_TF_DOCS_BLOCK -->
      {{ .Content }}
      <!-- END_AUTOMATED_TF_DOCS_BLOCK -->

sort:
  enabled: true
  by: required
settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
