### To generate the output file to partially incorporate in the README.md,
### Execute this command in the Terraform module's code folder:
# terraform-docs -c ../tfdocs-config.yml .

formatter: "markdown table" # this is required

header-from: "../_README_header.md"
footer-from: "../_README_footer.md"

content: |-
  {{ .Header }}
  ## Usage
  Basic usage of this module is as follows:
  ```hcl
    module "example" {
      {{"  "}} source  = "<module-path>"
  {{- if .Module.RequiredInputs }}
      {{"\n  "}} # Required variables
      {{- range .Module.RequiredInputs }}
      {{"  "}} {{ .Name }} =
      {{- end }}
      {{- end }}
  {{- if .Module.OptionalInputs }}
      {{"\n  "}} # Optional variables
      {{- range .Module.OptionalInputs }}
      {{"  "}} {{ .Name }} = {{ .GetValue | printf "%s" }}
      {{- end }}
      {{- end }}
    }
  ```
  {{ .Requirements }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Footer }}
output:
  file: ../README.md
  mode: inject
  template: |-
      <!-- BEGIN_AUTOMATED_TF_DOCS_BLOCK -->
      {{ .Content }}
      <!-- END_AUTOMATED_TF_DOCS_BLOCK -->
output-values:
  enabled: false
  from: ""
sort:
  enabled: true
  by: required
settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
